In [15]:
import numpy as np

def load_data():    
    # Goalkeeper, defender, midfielder, attacker
    possible_positions = ['GK', 'D', 'M', 'A']
    N = 100
    positions = []
    heights = []
    for i in range(0,N):
        positions.append(possible_positions[np.random.randint(len(possible_positions))])
        heights.append(np.random.normal(loc=180.0,scale=5.0))
    return positions, heights

positions, heights = load_data()

In [16]:
np_positions = np.array(positions)
np_positions

array(['D', 'GK', 'M', 'A', 'M', 'M', 'M', 'D', 'GK', 'A', 'GK', 'M',
       'GK', 'GK', 'GK', 'D', 'A', 'GK', 'A', 'M', 'D', 'D', 'A', 'M',
       'GK', 'A', 'A', 'D', 'M', 'A', 'GK', 'D', 'GK', 'M', 'A', 'M', 'M',
       'D', 'D', 'A', 'M', 'D', 'GK', 'M', 'GK', 'D', 'A', 'A', 'GK', 'A',
       'A', 'GK', 'D', 'A', 'GK', 'A', 'A', 'M', 'M', 'M', 'A', 'A', 'GK',
       'D', 'M', 'M', 'A', 'M', 'A', 'M', 'D', 'GK', 'D', 'A', 'A', 'M',
       'D', 'M', 'D', 'D', 'M', 'M', 'D', 'GK', 'GK', 'D', 'M', 'D', 'D',
       'M', 'M', 'A', 'A', 'M', 'A', 'M', 'M', 'D', 'M', 'M'], dtype='<U2')

In [14]:
np_heights = np.array(heights)
np_heights

array([182.57708199, 180.27579474, 182.15731541, 179.35905803,
       172.3926896 , 176.21804479, 181.19063483, 177.90693912,
       179.79707152, 179.52342737, 178.83842422, 178.98647141,
       171.75578173, 173.45814946, 183.49285816, 171.88732843,
       176.37531786, 179.23202509, 183.78201871, 185.14618805,
       184.19051814, 179.79932291, 176.06926984, 174.91129141,
       179.71973985, 184.12207974, 181.20464688, 181.20229043,
       187.05825915, 178.17283749, 181.09570664, 173.39754198,
       182.57119436, 177.71350138, 178.06419045, 180.51572777,
       175.67496121, 182.17022447, 171.08642084, 179.44299574,
       179.736426  , 178.93673064, 178.57759466, 188.66831444,
       177.03986886, 183.3625998 , 186.20965749, 179.53488184,
       179.04150537, 177.08220991, 180.92879159, 181.38673841,
       182.35297982, 177.9693248 , 189.56137426, 184.63098081,
       172.38886823, 183.03869243, 188.84668073, 186.55220716,
       183.86768649, 185.19026215, 189.22150105, 175.09

In [9]:
# Heights of the goalkeepers: gk_heights
gk_heights = np_heights[np_positions == 'GK']
gk_heights

array([182.92561082, 184.76645537, 178.76087217, 176.21164101,
       177.60410515, 173.60589712, 183.80722837, 188.37707803,
       172.84825546, 179.27522735, 177.89137954, 179.29914882,
       176.72334892, 186.53945735, 177.68963106, 178.65446667,
       179.3866774 , 176.88855795, 187.37340605, 180.63493338,
       176.60913347, 178.81288351, 178.6585742 , 181.26780162,
       176.23582647, 171.28803961, 177.64367275, 178.6912086 ,
       180.49853517, 187.13452686, 183.70727036, 184.60956216,
       173.79231046, 173.96193814, 183.59617187, 187.04868287,
       176.87542748, 181.15565179, 181.01945067, 185.86601148,
       173.24157466, 174.64435383, 181.86887597, 177.1514134 ,
       186.79618107, 171.86839667, 184.96133243, 178.06345849,
       188.09531682, 181.12997235, 178.41501687, 185.84090233,
       176.60860719, 186.17815054, 174.6272406 , 172.2275671 ,
       177.33005139, 176.84086863, 179.59683058, 178.87057365,
       183.93308641, 176.8609936 , 177.72852763, 175.97

In [10]:
# Heights of the other players: other_heights
other_heights = np_heights[np_positions != 'GK']
other_heights

array([182.92561082, 184.76645537, 178.76087217, 176.21164101,
       177.60410515, 173.60589712, 183.80722837, 188.37707803,
       172.84825546, 179.27522735, 177.89137954, 179.29914882,
       176.72334892, 186.53945735, 177.68963106, 178.65446667,
       179.3866774 , 176.88855795, 187.37340605, 180.63493338,
       176.60913347, 178.81288351, 178.6585742 , 181.26780162,
       176.23582647, 171.28803961, 177.64367275, 178.6912086 ,
       180.49853517, 187.13452686, 183.70727036, 184.60956216,
       173.79231046, 173.96193814, 183.59617187, 187.04868287,
       176.87542748, 181.15565179, 181.01945067, 185.86601148,
       173.24157466, 174.64435383, 181.86887597, 177.1514134 ,
       186.79618107, 171.86839667, 184.96133243, 178.06345849,
       188.09531682, 181.12997235, 178.41501687, 185.84090233,
       176.60860719, 186.17815054, 174.6272406 , 172.2275671 ,
       177.33005139, 176.84086863, 179.59683058, 178.87057365,
       183.93308641, 176.8609936 , 177.72852763, 175.97

In [11]:
# Print out the median height of goalkeepers.
print("Median height of goalkeepers: " + str(np.median(gk_heights)))

# Print out the median height of other players.
print("Median height of other players: " + str(np.median(other_heights)))

Median height of goalkeepers: 179.5509879647961
Median height of other players: 178.78687783960964


In [12]:
if(np.median(gk_heights) > np.median(other_heights)):
    print("The median goalkeepers height is bigger than that of the other players")
else:
    print("The median goalkeepers height is not bigger than that of the other players")

The median goalkeepers height is bigger than that of the other players
