In [2]:
import numpy as np
a = np.arange(5)
print(a)


[0 1 2 3 4]


In [3]:
a[[0,0,2]]=[1,2,3]
a


array([2, 1, 3, 3, 4])

In [5]:
a = np.arange(5)
a[[0,0,2]]+=1
a

array([1, 1, 3, 3, 4])

In [7]:
a=np.array([1])
b=a[:] #most simple slice a[0]
b[0]=0 # a[0]=0
a[0]==0

True

In [9]:
a=np.random.random((3)) #0 1 2
b= a[::-1] #a[-1]
b[0] = 1 #last elemen of a
b[0] == a[-1] 

True

In [13]:
a = np.random.random((3))
b = a #they will share data
b[0] = 1
b[0] == a[0]

True

In [16]:
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [15]:
b.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [18]:
a = np.random.random((3))
b = a[[0,1,2]] #copy of a, not slicing, it is fancy indexing
b[0] = 1 
b[0] == a[0]

False

In [22]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
ifancy = [0,2]
ifancy

[0, 2]

In [24]:
islice = slice(0,3,2)
islice

slice(0, 3, 2)

In [25]:
a[islice, :][:, ifancy] = 100
a

array([[100,   1, 100,   3],
       [  4,   5,   6,   7],
       [100,   9, 100,  11]])

In [28]:
b = np.arange(12).reshape(3,4)
ifancy = [0,2]
islice = slice(0,3,2)
b[ifancy, :][:, islice] = 100 #ifancy and islice are not interchangeable 
b #with ifancy we made a copy thats why original b is not changed

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])