# 1. Numpy exercises
### a. Create a null vector of size 10 but the fifth value which is 1

In [5]:
import numpy as np
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
print("Update fifth value to 1")
x[5] = 1
print(x)

Update fifth value to 1
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


### b. Create a vector with values ranging from 10 to 49

In [12]:
x = np.arange(10,49)
print("Original vector:")
print(x)

Original vector:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


### c. Reverse a vector (first element becomes last)

In [17]:
x = np.array([1,2,3,8,5])
reversed_x = arr[::-1]
print("Reversed vector:")
print(reversed_x)

Reversed vector:
[5 8 3 2 1]


### d. Create a 3x3 matrix with values ranging from 0 to 8

In [19]:
x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### e. Find indices of non-zero elements from [1,2,0,0,4,0]

In [25]:
x = np.array([1,2,0,0,4,0])
np.where(x==0)[0]

array([2, 3, 5])

### f. Create a random vector of size 30 and find the mean 

In [33]:
x = np.arange(0,30)
mean_x = np.mean(x)
print("Mean of vector:")
print(mean_x)

Mean of vector:
14.5


### g. Create a 2d array with 1 on the border and 0 inside
##### Two dimensional array is an array within an array. It is an array of arrays. In this type of array the position of an data element is referred by two indices instead of one. So it represents a table with rows an dcolumns of data.

In [39]:
x = [[1, 0, 1], [1, 0, 1]] 
x_array = np.array(x)
x_array

array([[1, 0, 1],
       [1, 0, 1]])

### h. Create a 8x8 matrix and fill it with a checkerboard pattern

In [77]:
import numpy as np
x = np.ones((3,3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [78]:
x = np.zeros((8,8),dtype=int)
x

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [79]:
print("Checkerboard pattern:")
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### i. Create a checkerboard 8x8 matrix using the tile function

In [82]:
# Python Program illustrating
# numpy.tile()
  
import numpy as np
  
x = np.ones((8,8))
print("arr : \n", x)
  
a = 0  
b = 1  
repetitions = (a, b)
print("\nRepeating arr : \n", np.tile(x, repetitions))
print("x Shape : \n", np.tile(x, repetitions).shape)
  

arr : 
 [[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]

Repeating arr : 
 []
x Shape : 
 (0, 8)
